### PR TITLE
feat: Add target SDK 30

### LINKED ISSUE #21: Add target SDK 30
Target SDK 30 is out :)

### PR DESCRIPTION
**Pull request by stephannielsen**
Also updates build tools for API 29 to 29.0.3.

Closes #21.

### CODE REVIEW

**Comment by stephannielsen** [comment]
I just followed the changes you made for adding SDK 29. I am fairly new to building docker images and not quite sure how to test the changes locally. Any pointers appreciated.

Running

```
docker build --tag mreichelt/android:30 --build-arg android_sdk_version=30 --file sdk.Dockerfile .
```

And then

```
docker run --rm -it mreichelt/android:30
```

seems to run just fine locally.

**Comment by stephannielsen** [comment]
@mreichelt did you have a change to look at the PR yet and have any plans to integrate it?

**Comment by alina-saetova** [comment]
@mreichelt

**Comment by omtodkar** [comment]
@mreichelt any plans on merging this pull request?

**Pull request merged**
